### ISSUE TITLE
Add support to create arrays of Objects

### ISSUE THREAD

**Issue by elingerojo** [zeke/html-frontmatter#14]
Arrays are limited to a single value per index.
It will be nice to have support for arrays of Objects so you can have multiple values per index.
It will be simple to add a ` JSON.parse() ` step that overrides the already parsed value (only if the input string happens to have a valid JSON syntax).

This will be an unobtrusive feature. No need to use it but nice to know that you can write JSON syntax at convenience.

**Comment by elingerojo** [comment]
` JSON.parse() ` was OK but YAML syntax is friendlier.

Changed to `npm js-yaml ` instead.

The approach is to ONLY parse with ` js-yaml ` if the two conditions are met.

1. The ` input ` look like YAML
2. is valid YAML

This way, we do not break anything.
If it does not look like YAML, the original parser kick in and everything is as usual.
If it looks like YAML, the original parser will not parse it anyway but now we can test if is a valid YAML and parse it.

Added a CI test for creating a couple of arrays of Objects in YAML

**Comment by elingerojo** [comment]
No longer needed for YAML support in [jus](http://jus.js.org/)

**Comment by zeke** [comment]
👍 Good thing I waited!
